on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: pramoddc.azurecr.io
        username: ${{ secrets.acr_pramoddc_username }}
        password: ${{ secrets.acr_pramoddc_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t pramoddc.azurecr.io/aks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push pramoddc.azurecr.io/aks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks8735 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks8735`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks8735
        container-registry-url: pramoddc.azurecr.io
        container-registry-username: ${{ secrets.acr_pramoddc_username }}
        container-registry-password: ${{ secrets.acr_pramoddc_password }}
        secret-name: aksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks8735
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
          manifests/ingress-2.yml
        images: |
          pramoddc.azurecr.io/aks:${{ github.sha }}
        imagepullsecrets: |
          aksdockerauth
